### ISSUE TITLE
Http failure response for https://prod.json.systems/v1/graphs:inferGraph: 0 Unknown Error

### ISSUE THREAD

**Issue by ComeonBug** [jsonsystems/json-schema#106]
![image](https://user-images.githubusercontent.com/18437542/100377556-6aa86280-304c-11eb-9d9c-216056142f2e.png)
when i submit my json data and after 5mins age , it will alert this message
[Http failure response for https://prod.json.systems/v1/graphs:inferGraph: 0 Unknown Error]
The following data is the json i just to submit , hope it can help you to figure out the bug
{
    "errcode": 0,
    "errmsg": "ok",
    "userlist": [{
        "userid": "zhangsan",
        "name": "张三",
        "department": [1, 2],
        "open_userid": "xxxxxx"
    }]
}

**Comment by jackwootton** [comment]
This has been fixed in the new version.
