### ISSUE TITLE
Cannot delete properties of the example

### ISSUE THREAD

**Issue by tillsanders** [jsonsystems/json-schema#107]
Maybe I'm missing something, but I find myself unable to delete properties of the example scheme. Whenever I try, I get the message `please infer a schema first`. I don't really know, what the problem is and I also don't understand, why I cannot start from scratch. I really like the project, but this and jsonsystems/public#18 make it currently unusable for me :( 

Can we maybe implement a button to start with a clean document and improve this error message?

**Comment by jsonsystems** [comment]
@tillsanders Thanks for submitting this issue. You just need to hit "submit" first to generate a schema because the first schema you see is just a placeholder.

**Comment by mkormendy** [comment]
But if you submit it again with your changes .. it reuses the old placeholder.

**Comment by jackwootton** [comment]
This should be fixed in the new version.
