### ISSUE TITLE
Manage Schemas never loads

### ISSUE THREAD

**Issue by nathandcornell** [jsonsystems/json-schema#108]
Just spins forever:
![Screen Shot 2021-01-26 at 17 11 29](https://user-images.githubusercontent.com/2002882/105927864-b4380e00-5ff9-11eb-9824-a74f59dddbf8.png)

Tried as a guest, as well as logged in via Github.
Both on Chrome and Firefox

**Comment by nadavofi** [comment]
me too - endless spinner and nothing in the network tab nor browser's console

**Comment by jackwootton** [comment]
This should be fixed in the new version.
