### ISSUE TITLE
Recommendations for encouraging correct usage and good practices for $id

### ISSUE THREAD

**Issue by jdesrosiers** [jsonsystems/json-schema#112]
The schemas created on https://www.jsonschema.net don't use `$id` properly. We (the JSON Schema core team) see this leading to not only incorrect schemas, but also confusion about how `$id` works. We hope you'll consider making the following changes to your `$id` generation options to help encourage correct usage and good practices. Thanks for your consideration.

### JSON Pointer Fragment
Because this is the default mode, we see this constantly. Unfortunately, it's invalid. A JSON Pointer is not allowed to be an anchor because `/` is not an allowed character for anchors. Which is good, because otherwise implementations wouldn't be able to tell the difference and wouldn't know how to process it correctly.

> This value MUST begin with the number sign that specifies a fragment ("#"), then a letter ([A-Za-z]), followed by any number of letters, digits ([0-9]), hyphens ("-"), underscores ("_"), colons (":"), or periods (".").
> - https://tools.ietf.org/html/draft-handrews-json-schema-01#section-8.2.3

Even if it was valid to have a JSON Pointer as an anchor, it would at best be a no-op to have an anchor that is the same as the JSON Pointer you would otherwise use to reference that part of the schema. It gets worse if you have a JSON Pointer anchor that doesn't match its actual location in the schema. Should an implementation go to JSON Pointer location, or the contradictorily named anchor?

_Recommendation:_ Remove this option entirely. It's invalid, unnecessary, and error prone.

### Plain Name Fragment
This option sets anchors correctly except that it doesn't create unique names. Here's an example of a generated schema with conflicting anchors.

_Instance_
```json
{
  "foo": {
    "foo": "bar"
  }
}
```
_Generated Schema_
```json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "http://example.com/example.json",
  "type": "object",
  "properties": {
    "foo": {
      "$id": "#foo",
      "type": "object",
      "properties": {
        "foo": {
          "$id": "#foo",
          "type": "string"
        }
      }
    }
  }
}
```
`#foo` points to both `/properties/foo` and `/properties/foo/properties/foo`. You can't be sure which one you're going to get when you reference it.

But even if you are generating unique names, setting anchors everywhere is unnecessary noise. Anchors are best applied on a case-by-case basis. The only rule that I think makes sense for setting anchors would be to say that all `definitions` should have an anchor. But, as far as I can tell, this tool never generates `definitions`.

_Recommendation:_ Fix or remove this option. If you fix the unique name problem, then there's nothing technically wrong with this option. However, there's also no value in setting anchors everywhere, so it should really never be used.

### Base URI
The generous interpretation is that this is the same thing as the "JSON Pointer Fragment" option except more verbose. When defining a plain name fragment, it must start with a `#`. However, you could say that the `"$id": "http://example.com/example.json#/properties/foo"` is equivalent to `"$id": "#/properties/foo"` when the schema's URI is `http://example.com/example.json`.

Otherwise, you have to interpret it as a schema identifier, which means the fragment is not interpreted as a plain name fragment and you have a naming conflict where the root schema and the sub-schema have the same identifier. In the most recent drafts, it is explicitly forbidden for an `$id` to have a fragment. You also have the problem that schema identifiers change the resolution scope which causes confusing bugs (especially for beginners) when developers refactor or add to the generated schema with `definitions` and `$ref`s.

_Recommendation_: Remove this option. The behavior in the this case is ambiguous at best. Either way, no one should be using `$id`s this way for any reason.

### None
The only problem with this option is that it not only leaves out `$id`s from sub-schemas, it also leaves out the absolute `$id` at the root of the schema. That root `$id` is not necessary, but if it's set in the settings, we would expect it to be included in the generated schema no matter what other options are selected.

_Recommendation:_ This should be the default option or the only option and it should not suppressed the root `$id`.

**Comment by jdesrosiers** [comment]
> It gets worse if you have a JSON Pointer anchor that doesn't match its actual location in the schema. Should an implementation go to JSON Pointer location, or the contradictorily named anchor?

Here's a link to a recent example that illustrates this problem, https://stackoverflow.com/questions/69050877.

Please, please, please address this bug. It causes the JSON Schema support community so much time and effort to repeatedly explain the problem and tell people to delete the `$id`s that this tool generates. Even if all you can do is make the default "None", that would go a very long way to alleviate this problem.

**Comment by jackwootton** [comment]
Thanks for the feedback. This is addressed in a new version of the web application that we hope to publish soon. In fact we've already incorporated it into the new version...it's just not generally available right now.

**Comment by mkyc** [comment]
@jdesrosiers we (jsonschema.net) also have experimental alpha version of command line tool that uses exactly the same engine as web application mentioned by @jackwootton. I was wondering if you (or someone form your org) would like to test it.

**Comment by jdesrosiers** [comment]
@mkyc I'd be happy to try it out and give feedback, but not for another 2 weeks. I have a deadline to make at the moment that takes priority.

**Comment by jackwootton** [comment]
This has been fixed in the new version available at www.jsonschema.net.
