### ISSUE TITLE
trouble logging in

### ISSUE THREAD

**Issue by lishenfan** [jsonsystems/json-schema#116]
Prompt timeout
![image](https://user-images.githubusercontent.com/85975189/122147023-aee53e00-ce8a-11eb-9ee8-ee1ac05f5e14.png)

**Comment by jackwootton** [comment]
@lishenfan Thanks for posting this issue. Are you logging in anonymously? I've just checked and it worked for me. Can you provide your browser info?

**Comment by lishenfan** [comment]
google chrome   91.0.4472.106

**Comment by jackwootton** [comment]
Any login issues should be resolved with the new version. If you're still experiencing issues, please open a new issue at https://github.com/jsonsystems/public
