### ISSUE TITLE
Load json schema directly from an url

### ISSUE THREAD

**Issue by psss** [jsonsystems/json-schema#19]
It would be nice to able to directly open a json schema by providing an url, for example:

    https://jsonschema.net/?url=url_to_a_public_json_schema

This would be a very useful feature. The edit mode nicely shows the schema structure so it could be used for nicely visualizing existing schemas and experimenting with them.

**Comment by jsonsystems** [comment]
@psss the ability to load schema has been removed from www.jsonschema.net to focus development on inferring and editing only.
