### ISSUE TITLE
Problem with documents:infer service - returns 500 error

### ISSUE THREAD

**Issue by marekkaczkowski** [jsonsystems/json-schema#23]
There is some problem with https://prod.json.systems/v1/documents:infer
You can try Submit default schema (Schema tab)
```
xxx=token
POST https://prod.json.systems/v1/documents:infer?key=xxx 500 ()
(index):1 Failed to load https://prod.json.systems/v1/documents:infer?key=xxx:
No 'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'https://jsonschema.net' is therefore not allowed access. The response had HTTP status code 500.
```

**Comment by jackwootton** [comment]
Thanks for taking the time to report this. Is it still a problem for you?  I can't recreate the issue, but that's not to say other people aren't experiencing it.

**Comment by marekkaczkowski** [comment]
We can close it, looks like it was temp. server problem.
Thanks for repl Jack

**Comment by joeskeen** [comment]
@jsonsystems It seems that this issue has surfaced again.  I've tried a few different JSON samples, and I always get the same 500 error
![image](https://user-images.githubusercontent.com/12286274/89235409-55925a00-d5ab-11ea-8db2-f59ec6848a34.png)

**Comment by jsonsystems** [comment]
@joeskeen Thank you for posting this issue.

I just tried this with the developer tools open and cache disabled and it works for me. Can you provide your browser details please? And when did this last work for you?

**Comment by mdornseif** [comment]
I have seen it the last tree days, eg just now: Thu Aug 27 22:26:12 CEST 2020
Logging out and back in did not help.
Tried Chrome and Safari on Mac OS.

**Comment by jsonsystems** [comment]
@mdornseif Thanks for this information. Looks like it could be related to the JWT used for authentication (`incorrect padding` and because it worked when logged in with a guest session).

**Comment by jsonsystems** [comment]
@mdornseif this should now be working, can you try www.jsonschema.net?
