### ISSUE TITLE
Save Configuration to Local Storage

### ISSUE THREAD

**Issue by p0fi** [jsonsystems/json-schema#26]
When dealing with JSON Schemas and thus with jsonschema.net as a schema generator it would be really helpful if the general configuration ( Annotations > Infer Title, Infer Description, Infer Default, Infer Examples,...etc) could be saved somehow.

I for example never want these kind of information in my schema and I need to uncheck and correct the settings each time I visit the site for a new schema. :(

**Comment by jsonsystems** [comment]
Duplicate of #4
