### ISSUE TITLE
support multiple files/ batch mode?

### ISSUE THREAD

**Issue by guidorice** [jsonsystems/json-schema#31]
I have a folder full of json data files, and would prefer to use jsonschema.net because I think it produces good output. This does not seem to be possible through the https://www.jsonschema.net/ web app.

For comparison, this other tool for the cli, supports a batch mode:
https://github.com/snowplow/schema-guru

**Comment by jackwootton** [comment]
File uploading and URL loading are frequently requested and I'm keen to implement both. You're right of course, this is not currently possible. However, with the advent of user login (on the road-map for this year),  file upload / batch upload will be pretty easy to implement.

You may also be interested in a REST API which JSONschema.net currently uses. I plan on providing access to the API for individuals to play around with. If you don't mind integrating with REST over HTTP, this will arrive sooner than file upload/batch schema generation.

**Comment by guidorice** [comment]
@jackwootton, ah ok, so I am currently doing a on-off project, so integrating with REST API might be overkill for my use case. Thanks for letting me know though!

I guess this feature request is specifically:

multiple json instances -> derive single json schema

thanks much!

**Comment by jackwootton** [comment]
@guidorice Thanks for clarifying. Do you have any rules or protocol in mind when combining multiple JSON instances into a single, derived, JSON schema?

**Comment by jackwootton** [comment]
@guidorice https://github.com/jsonsystems/public/issues/9 tracks `enum`.
