### ISSUE TITLE
maxLenght not displayed in schema

### ISSUE THREAD

**Issue by SeamonLark** [jsonsystems/json-schema#67]
When I edit an string object and set the minLength and maxLength values.
The minLength is displayed correctly, but the maxLength is missing.

example - maxLength is 30, but it isn't displayed:
        "company_name": {
            "$id": "#/properties/company_name",
            "type": "string",
            "readOnly": false,
            "writeOnly": false,
            "minLength": 10,
            "title": "The Company_name Schema",
            "description": "Názov spoločnosti",
            "default": ""
        }

**Comment by jackwootton** [comment]
Thanks for reporting this. I'll start work on a fix immediately.

**Comment by jsonsystems** [comment]
This is now fixed in the live version.
