### ISSUE TITLE
No settings for additional properties

### ISSUE THREAD

**Issue by lailatulrizqi22** [jsonsystems/json-schema#70]
<img width="702" alt="Screen Shot 2020-03-04 at 09 37 07" src="https://user-images.githubusercontent.com/55479376/75839597-c74b5980-5dfb-11ea-8597-12ff31c8ecc7.png">

**Comment by jackwootton** [comment]
The default value for `additionalProperties` is `true`, and this can be shown by using the verbose toggle. I guess what you're looking for is a way to add this to all objects?

Question: If the checkbox is `true`, since this is the default, would you expect it to be visible in the schema? Or would it only be visible if it was `false` (i.e. unchecked)?

**Comment by bestwebua** [comment]
@jackwootton, I'm looking for is a way to add this to all objects :)

**Comment by jackwootton** [comment]
@bestwebua How would a user turn this off if they didn't want it visible for all objects?

**Comment by bestwebua** [comment]
Like now. Maybe should add additional properties options toggle below the objects option?

**Comment by hanikhan** [comment]
this feature is a must have. It was there on the old interface. The current workaround adds a lot of redundant keys. Let me know if I can help here, would love to contribute since I use it so extensively.

**Comment by jsonsystems** [comment]
@bestwebua the issue here is whether toggling-**on** additional properties should show `true` or nothing. This is why I have added the `verbose` toggle on the output panel, i.e.

```json
# Always display this (there is no default).
additional_properties: false

# Only show this if the user has toggled-on verbose.
additional_properties: true
```

Despite it being a boolean, there are three states:

- false
- true (explicit)
- true (implied)

**Comment by hanikhan** [comment]
Just a thought: Can we add `Display AdditionProperties` in the `INFER` section with a toggle for true/false. If the user chooses this option in `INFER` section, the toggle will let them decide. Else, the verbose implementation stands.

**Comment by jsonsystems** [comment]
@hanikhan not a bad idea, but this would have to be repeated for `additionalItems` and any other keyword that has a default value. We would end-up with two checkboxes for every boolean keyword (one denoting the **value**, and the other the **visibility**)

**Comment by bestwebua** [comment]
@jsonsystems I really like hanikhan's suggestion too.

**Comment by jsonsystems** [comment]
How about something like this?

![image](https://user-images.githubusercontent.com/1623996/78530219-2c1f1880-77db-11ea-8f82-9b379f0c52a9.png)

**Comment by bestwebua** [comment]
Make sense :+1:

**Comment by jsonsystems** [comment]
@bestwebua @hanikhan @lailatulrizqi22 I've just released an update with this feature. Let me know if this works for you?

**Comment by bestwebua** [comment]
@jsonsystems It works like a charm! :1st_place_medal: Brilliant! :+1: :+1: :+1:
