### ISSUE TITLE
anyOf, oneOf and allOf fields are not shown in the visual view

### ISSUE THREAD

**Issue by kasvtv** [jsonsystems/json-schema#71]
In JSON schemas, instead of having a `type` for a property, one can have things like [as described on this page](https://json-schema.org/understanding-json-schema/reference/combining.html):

```
      "anyOf": [{"type": "string"}, {"type": "null"}],

```

These cases are not shown at all in the visual view, it implies the type is missing.

**Comment by jackwootton** [comment]
@kasvtv Thanks for flagging this. When you say "visual view" - do you mean the editable view. If so, how would you like these **logical** and **conditional** keywords presented? Would you like them to be editable too?

**Comment by kasvtv** [comment]
Excuse the late reply. I don't mind the editability as much, it mostly hurts not having oversight. On the right-hand side, in the view accessed by clicking the pencil icon, it implies there is no type data available whatsoever in this example case.

**Comment by jsonsystems** [comment]
@kasvtv The ability to load a schema has been removed from www.jsonschema.net for now while a better implementation is developed. I'll close this issue since it doesn't not impact inferring schema from JSON or editing schema.
