### ISSUE TITLE
Adding enum values in the property editor does not update the schema

### ISSUE THREAD

**Issue by bwesterhaus** [jsonsystems/json-schema#72]
If loading a schema with enum values, they are loaded into the property editor, but adding enum values or adding an enum to a property that does not have one does not update the schema.

**Comment by jackwootton** [comment]
@bwesterhaus Thanks for flagging this. Itn has the same underlying cause as https://github.com/jackwootton/json-schema/issues/67

I'll leave this open for verification purposes.

**Comment by jsonsystems** [comment]
@bwesterhaus This is now fixed on www.jsonschema.net

![image](https://user-images.githubusercontent.com/1623996/88464232-9356fa80-cea8-11ea-89e3-3284f48688fc.png)
