### ISSUE TITLE
CLI for generating JSON Schema from JSON

### ISSUE THREAD

**Issue by abdul-thoughtworks** [jsonsystems/json-schema#73]
Do we have a CLI for generating JSON Schema from JSON, This would be highly beneficial .

**Comment by jackwootton** [comment]
Thanks for the feature request. Eventually I would like to package the application so it can be installed with pip. However right now my focus is on the web application so less technical users can just copy-paste without coding knowledge.

I'll tag this as an enhancement to track it.

**Comment by pmgupte** [comment]
+1 for FR. I am planning to improve (drastically) my [content monitoring utility](https://github.com/pmgupte/webmon/blob/master/README.md) pet project, and wanted exactly what you have here! If CLI is available, I would like to use it in the planned improvement.

**Comment by rquintanilla-amp** [comment]
Or just some NPM modules so that we can call this programmatically?

**Comment by jsonsystems** [comment]
Duplicate of #30.

Thanks for expressing an interest in the source code or a package. To avoid this slipping down my list again I'm merging with #30.
