### ISSUE TITLE
"type": "null" is missing when response JSON any key has null value

### ISSUE THREAD

**Issue by hitesh010** [jsonsystems/json-schema#74]
"type": "null" is missing when response JSON any key has null value. 

If a key is null in response, in schema - 
1. type of the key should be there 
2. Initially null can be given i.e. "type": "null"

In your previous implementation, this was there and it used to help when there was an update in value let say from null to String/Integer ,we came to know. I think this needs to be added. Thanks.

**Comment by jackwootton** [comment]
@hitesh010 Thanks for reporting this. This is a bug.
```json
{
    "foo": null
}
```

Should yield:
```json
{
    "type": "object",
    "properties": {
        "foo": {
            "type": "null"
        }
    }
}

**Comment by jackwootton** [comment]
This has been fixed in the next release (not yet deployed):

![image](https://user-images.githubusercontent.com/1623996/76806647-ea9ddd80-67d9-11ea-96af-2bc81a3ccac3.png)

**Comment by jsonsystems** [comment]
I've just released a new version which fixes this.
