### ISSUE TITLE
generate jsonschema went wrong

### ISSUE THREAD

**Issue by wuyinping** [jsonsystems/json-schema#75]
help 
it went wrong when i use it to generate jsonschema 
it toasts  someting went wrong 
it takes soooooooo  long a time

**Comment by jsonsystems** [comment]
@wuyinping Can you provide the steps to recreate this issue?

**Comment by qinzhen666** [comment]
I encountered the same problem：
1、Enter json content in infer schema
2、click ”SUBMIT“button
3、then it takes soooooooo long a time and toasts someting went wrong
![image](https://user-images.githubusercontent.com/45816634/78118802-1657cf00-743a-11ea-9adc-f34ebe24eaa3.png)

**Comment by jsonsystems** [comment]
Can you provide your JSON so I can attempt to recreate the issue?

**Comment by cyc1ingsir** [comment]
This happens even if you click on RESET and the clicking on SUBMIT

**Comment by ohde** [comment]
I am also getting the same error with the default JSON that is loaded. I have attached a screenshot of my console output. Thanks for your support. 

<img width="1580" alt="json_schema_console" src="https://user-images.githubusercontent.com/6856263/79873070-74be0080-839b-11ea-8a83-f4bf234fe6bf.png">

**Comment by jsonsystems** [comment]
I broke CORS. Can you use https://jsonschema.net/ for now?

**Comment by jsonsystems** [comment]
Closing this because the OP hasn't provided more information.
