### ISSUE TITLE
How to Generate POCO and Sql Create Table on the fly

### ISSUE THREAD

**Issue by weedkiller** [jsonsystems/json-schema#76]
Hello, this is a great lib. I am looking to use it, but I cant figure out how to get the C# objects at run time and create SQL tables on the fly.

Essentially, we have user created surveys forms that live for a week we need to store those forms from JSON.

thanks

**Comment by jsonsystems** [comment]
@weedkiller It sounds like you have questions about a system unrelated to www.jsonschema.net. I'm unsure how I can help here.
