### ISSUE TITLE
Exception calling application: ID type is ID_TYPE_NONE when "Identifier Type" is "None"

### ISSUE THREAD

**Issue by wkopen** [jsonsystems/json-schema#80]
Looks like it will always throw `Exception calling application: ID type is ID_TYPE_NONE` when "Identifier Type" is "None". Is this a bug?

**Comment by jsonsystems** [comment]
Yes. Let me get on that. Thanks for taking the time to report this.

**Comment by jsonsystems** [comment]
This is now fixed on www.jsonschema.net. Thank you for reporting it.
