### ISSUE TITLE
Settings Displaying incorrectly on Safari

### ISSUE THREAD

**Issue by donavanbecker** [jsonsystems/json-schema#82]
<img width="1439" alt="Screen Shot 2020-05-06 at 8 29 14 AM" src="https://user-images.githubusercontent.com/9875439/81182641-afb35d00-8f73-11ea-8f37-1ab2e4c419bb.png">

**Comment by jsonsystems** [comment]
@donavanbecker A fix for this is now live. Thanks for taking the time to report this.
