### ISSUE TITLE
Typo in 'additionalProperties'

### ISSUE THREAD

**Issue by hmemcpy** [jsonsystems/json-schema#83]
Hello. Just tried the site, and noticed that `additionalPropreties` was misspelled in the generated schema, it says 'propeties' instead

**Comment by jsonsystems** [comment]
@hmemcpy Thanks for reporting this. I'll get a fix for it out this week.

**Comment by jsonsystems** [comment]
@hmemcpy I've just deployed a fix for this. If you could confirm, then I'll close this issue.
