### ISSUE TITLE
API not available?

### ISSUE THREAD

**Issue by crubier** [jsonsystems/json-schema#87]
![Screenshot 2020-06-15 at 11 43 26](https://user-images.githubusercontent.com/2954572/84648834-78828500-aefd-11ea-832b-bf0c41c9038e.jpg)

**Comment by jsonsystems** [comment]
@crubier This works for me. Are you able to provide the referer URL from Chrome/Firefox developer console?

**Comment by crubier** [comment]
Ok got it, I was using Brave Browser with Shield on. This cause some Auth problems with some websites. Can close, sorry

**Comment by jsonsystems** [comment]
@crubier No worrries. I'm going to leave this open while I investigste this further. You're not the first to have this problem. I'll update this issue when I have some more information. Thank you for taking the time to post it too.

**Comment by jsonsystems** [comment]
OK, so Brave blocks cross-site cookies but www.jsonschema.net uses an API hosted on `https://json.systems` and so the cookie is blocked. Both the frontend and backend are developed by me, it's just that they're quite separate (hence the differen domains).

**Comment by jsonsystems** [comment]
This should now work in Brave. I tested with `Version 1.11.104 Chromium: 84.0.4147.105 (Official Build) unknown (64-bit)`.
