### ISSUE TITLE
$id in schema generated is not uri compatible if there is space in json key

### ISSUE THREAD

**Issue by ashudream11** [jsonsystems/json-schema#89]
**sample json**

> {
    "space in key": false
}

**generated schema** (Issue is highlighted in schema)

> {
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "object",
    "title": "The root schema",
    "description": "The root schema comprises the entire JSON document.",
    "default": {},
    "examples": [
        {
            "space in key": false
        }
    ],
    "required": [
        "space in key"
    ],
    "additionalProperties": true,
    "properties": {
        "space in key": {
            `"$id": "#/properties/space in key",` **-> Issue** ,   **expected** -> `"$id": "#/properties/space%20in%20key",`
            "type": "boolean",
            "title": "The space in key schema",
            "description": "An explanation about the purpose of this instance.",
            "default": false,
            "examples": [
                false
            ]
        }
    }
}

**Comment by jsonsystems** [comment]
Thanks for reporting this. I'll ensure it's fixed in the next release. I'll leave this open for tracking purposes.

**Comment by jsonsystems** [comment]
@ashudream11 This should now be fixed on www.jsonschema.net

![image](https://user-images.githubusercontent.com/1623996/88464619-dbc3e780-ceab-11ea-9cc1-3eb2b51bb848.png)
