### ISSUE TITLE
Github OAuth login broken in Firefox

### ISSUE THREAD

**Issue by clusin** [jsonsystems/json-schema#92]
Issues:
1. Popup blocked automatically
2. After granting access doesn't redirect to authenticated site.

Firefox version 78.0.2 (64-bit)

**Comment by jsonsystems** [comment]
@clusin Thanks for taking the time to report this. I just did a quick test on a Mac with Firefox 78.0.2 (64 bit) and this worked for me (although the popup was blocked to start with). After enabling popups for jsonschema.net, it worked as expected.

I'll conduct more tests later today, this was just a quick informal test.

**Comment by clusin** [comment]
Thanks. Experimenting a little bit more it looks like µBlock Origin (ad blocker) is the culprit.

**Comment by jsonsystems** [comment]
@clusin I installed ublock (1.28.4) on Firefox (77.0.1 (64-bit)) and I could login using GitHub federated login on www.jsonschema.net. However, I was only using the default settings for ublock. Are there any specific settings I should have set for ublock?
