### ISSUE TITLE
Not able to signup on jsonschema.net as it is showing lowrecaptcha score.

### ISSUE THREAD

**Issue by Archana301189** [jsonsystems/json-schema#95]
Not able to signup on jsonschema.net as it is showing lowrecaptcha score.tried using Github login too then to not working

**Comment by jsonsystems** [comment]
@Archana301189 Thanks for this issue. Can you provide details on your browser and whether you have any ad blockers installed?

**Comment by titpetric** [comment]
Version 79.0.3945.130 (Developer Build) built on Debian buster/sid, running on Debian buster/sid (64-bit)

AdBlock installed.

**Comment by jsonsystems** [comment]
@titpetric Thanks for the detail, which browser are you using?

**Comment by titpetric** [comment]
That’s a Chromium, weirdly I assumed it was in the version string 😂

**Comment by jsonsystems** [comment]
@titpetric Can you disable adblock, register, enable adblock, and then login?

**Comment by titpetric** [comment]
I don’t want to register, but thanks.

**Comment by jsonsystems** [comment]
@titpetric Sure thing. I assumed that you had tried to do so in order to receive the low recaptcha score :/

**Comment by titpetric** [comment]
Nope, that’s immediate - i wanted to use the guest login link below the
signup form. The notice pops up without interaction (or possibly from a
click on the guest link).

**Comment by Detnator-Neo** [comment]
Hi there.For what it's worth, I'm having the same issue.  My setup: macOS catalina 10.15.6.  Safari 13.1.2 and Safari Technology Preview 14.0.1.  It seems to be working in Chrome.  Also it worked once or twice in Safari but then stopped working.  So intermittent issue of some kind, it seems.

**Comment by jsonsystems** [comment]
@Detnator-Neo I tested this morning with macOS Catalinaa 10.15.6 with Safari 13.1.2;

Worked:
- Signing up for a new account and logging in
- Logging in with GitHub which worked (although Safari did block the pop-up)

Not working:
- Continuing as a Guest (low reCAPTCHA score)

```
{
    "success": true,
    "score": 0.7,
    "action": "login",
    "challenge_ts": "2020-09-12T09:37:17Z",
    "hostname": "jsonschema.net",
    "error-codes": null
}
```

I will take the lower bound down to 0.7 and see if that is the right balance between security and permissiveness

**Comment by jsonsystems** [comment]
I've changed the threshold so this should now be working. Let me know?

**Comment by fernandolguevara** [comment]
same problem here, can't use the tool 
![image](https://user-images.githubusercontent.com/969516/97460598-ab14a380-191b-11eb-87ea-07b5005d6be6.png)

**Comment by jsonsystems** [comment]
@fernandolguevara What is the response from the recaptcha request (`https://jsonschema.net/api/captcha`)?

**Comment by fernandolguevara** [comment]
![image](https://user-images.githubusercontent.com/969516/99971953-ac9b8500-2d7c-11eb-9d97-d15e8261faf6.png)

**Comment by jsonsystems** [comment]
@fernandolguevara 0.1 is a very low score. Are you using an ad-blocker, or Brave with Shields Up? I don't know the algorithm behind [recaptcha v3](https://developers.google.com/recaptcha/docs/v3) but I think it scores can be impacted by browser settings.

Can you try in a standard Chrome install without any extensions installed and see if that works for you? Or perhaps in Incognito mode?

**Comment by fernandolguevara** [comment]
No problem, it's a shame that I can't use the tool, I don't know exactly what's behind the user's system, but it would be nice if anonymous users can use the tool ✌🏼

**Comment by jsonsystems** [comment]
@fernandolguevara I would like that too. Did you try in a standard Chrome brower install without any extensions installed and see if that works for you?

**Comment by jackwootton** [comment]
This should now be resolved on the new version of www.jsonschema.net
