### ISSUE TITLE
Downloadable/offline version of this?

### ISSUE THREAD

**Issue by Detnator-Neo** [jsonsystems/json-schema#98]
Hi there. Not sure the best place to post this question.  Apologies if this is *not* the place.  If so, can someone point me in the right direction please?  That said...

What this does, when it works, is pretty awesome.  But... are there any apps that can do this offline?  Particularly I'm on macOS, so preferably a Mac app.

An app that I can install and have it be able to - offline, not requesting results from an online API or whatever - (1) generate JSON schema from JSON I type/paste in, and (b) validate entered json against entered schema.

If such a thing exists I'd appreciate being pointed to it.  Thanks!

**Comment by jsonsystems** [comment]
@Detnator-Neo Good question. I'm currently playing around with a Go version, but it's just a prototype at the moment. However, would a command line version (with flags, etc) work for you?

**Comment by Detnator-Neo** [comment]
A GUI version would be great of course, so would love you to keep working on that. 😊  But yes I can handle a command line version (with some explanation of the usage, flags, options, etc.) for sure.  That'd be awesome.  Thanks!

**Comment by NashiCoding** [comment]
> @Detnator-Neo Good question. I'm currently playing around with a Go version, but it's just a prototype at the moment. However, would a command line version (with flags, etc) work for you?

It sounds great. Thanks a lot for your outstanding work. How can i install this tool on local? 
Because i worked in a lan environment, it's not easy to visit website to use it.  Look forward to your reply.

**Comment by jackwootton** [comment]
With the latest version there is a [CLI](https://github.com/jsonsystems/public#cli) and [API](https://github.com/jsonsystems/public#api). This repo will shortly be archived so please post new issues at https://github.com/jsonsystems/public. Thanks.
