### ISSUE TITLE
Keywords Starting With $ are Removed After Updating The Schema

### ISSUE THREAD

**Issue by kkadir** [jsonsystems/json-schema#99]
**Steps to Reproduce**
1. Use any valid JSON to generate a schema.
2. On the JSON Schema panel, switch to the Edit View.
3. Click Edit on any element, i.e. root.
3. Change any attribute, i.e. update the Required list.
4. Click Save and switch back to the Code View.
5. Observe that keywords like `$schema`, `$id`, and etc. do not exist anymore.

**Screenshots**
Before editing anything, i.e. the required list:
![image](https://user-images.githubusercontent.com/8139167/93615137-af27da00-f9db-11ea-8e2f-adda0d7a97e8.png)

After saving the change (1 & 2) observe that the  `$schema` and `$id` fields are gone (3):
![image](https://user-images.githubusercontent.com/8139167/93615412-03cb5500-f9dc-11ea-8811-1268a87d0c38.png)

**Comment by jsonsystems** [comment]
@kkadir Thank you for posting this in detail and with clear steps to recreate. I can confirm I can recreate this. I'll look at it this weekend and hopefully release a fix too. I will update this thread with my progress this weekend.

**Comment by jsonsystems** [comment]
@kkadir This should now be fixed on www.jsonschema.net. Apologies for the delay in getting round to this.

**Comment by kkadir** [comment]
Thank you, seems to work now properly, closing this issue now!
